# Generated by Django 4.2.8 on 2024-01-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_user', '0002_bankaccount_kycinformation_transaction_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_kyc',
            field=models.BooleanField(default=False),
        ),
    ]
