# Generated by Django 4.2.8 on 2024-01-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_user', '0003_userprofile_is_kyc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycinformation',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_kyc',
        ),
        migrations.AddField(
            model_name='kycinformation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycinformation',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
