# Generated by Django 4.2.8 on 2024-01-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_user', '0004_alter_kycinformation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_kyc',
            field=models.BooleanField(default=False),
        ),
    ]
