# Generated by Django 4.2.8 on 2024-01-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_user', '0007_remove_userwallet_coin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usercryptowallet',
            name='coin_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usercryptowallet',
            name='coin_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
