# Generated by Django 4.2.8 on 2024-01-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_user', '0009_usercryptowallet_coin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercryptowallet',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
