# Generated by Django 4.2.8 on 2024-01-23 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_user', '0013_remove_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='CoinTransaction',
        ),
    ]
