# Generated by Django 4.2.8 on 2024-01-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_user', '0014_rename_transaction_cointransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cointransaction',
            name='user_profile',
        ),
    ]
