# Generated by Django 4.2.8 on 2024-01-23 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_user', '0016_alter_cointransaction_coin_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='coin_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_user.usercryptowallet'),
        ),
    ]
