# Generated by Django 4.2.8 on 2024-01-23 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_user', '0018_cointransaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cointransaction',
            name='coin_details',
        ),
        migrations.RemoveField(
            model_name='cointransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='coin_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='coin_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='coin_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='coin_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='profitandloss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='userwallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crypto_user.userwallet'),
            preserve_default=False,
        ),
    ]
