# Generated by Django 4.2.8 on 2024-01-24 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_user', '0019_remove_cointransaction_coin_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ammount', models.FloatField(default=0.0)),
                ('status', models.CharField(max_length=20)),
                ('userwallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_user.userwallet')),
            ],
        ),
    ]
