# Generated by Django 4.2.8 on 2024-01-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_user', '0020_fundtransactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundtransactions',
            old_name='ammount',
            new_name='amount',
        ),
    ]
