# Generated by Django 4.2.8 on 2024-01-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_user', '0022_updatecoindetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatecoindetails',
            old_name='coin_details',
            new_name='user_crypto_wallet',
        ),
    ]
